[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "temenosAccountArrangements"
version = "0.1.0"
license = ["Apache-2.0"]
authors = ["iamSahdoon"]
keywords = ["banking", "temenos", "api", "account arrangements"]
repository = "https://github.com/iamSahdoon/module-ballerinax-temenosAccountArrangements"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
